feat(unify modules): merged widget with module
rrpproxy/whmcs-rrpproxy-registrar pull request #100
Opened 2022-08-01 12:28 UTC by AsifNawaz-cnic

2022-08-01 18:02 UTC, KaiSchwarz-cnic requested changes
See my comments below.

plus: in keysystems.php, there's a line `require_once __DIR__ . '/vendor/autoload.php';` which represents the autload functionality of composer. Would you mind checking if loading of libraries also works if this line is not present? Feel free to discuss this with me for clarification.

2022-08-02 10:26 UTC, AsifNawaz-cnic commented on modules/registrars/keysystems/keysystems.php
>  function keysystems_getAccountDetails(): array
Thanks for notifying me, I have reverted my changes and applied Sebastian's changes.

2022-08-02 12:33 UTC, AsifNawaz-cnic commented
> See my comments below.
> 
> plus: in keysystems.php, there's a line `require_once __DIR__ . '/vendor/autoload.php';` which represents the autload functionality of composer. Would you mind checking if loading of libraries also works if this line is not present? Feel free to discuss this with me for clarification.

Tried but did not worked, will need to create a separate task for this.

2022-08-02 12:38 UTC, AsifNawaz-cnic reviewed
Allowing dependabot to execute test.yml on pushes on all branches to lint the code and also resolved the conflicts.

2022-08-05 07:18 UTC, KaiSchwarz-cnic commented
> Tried but did not work, will need to create a separate task for this.

Task created & added to backlog.

2022-11-14 12:18 UTC, closed without merging