feat(tldsync): implement tld pricing sync
rrpproxy/whmcs-rrpproxy-registrar pull request #12
Opened 2020-08-20 16:41 UTC by h9k

2020-08-24 13:06 UTC, papakai requested changes

2020-08-24 13:06 UTC, papakai commented on modules/registrars/rrpproxy/sql/mod_rrpproxy_zones.php
> +$mod_rrpproxy_zones = array(
more a question: looks like manual work to get this aligned to the RRPproxy backend system. might be a topic for build process to to get this automated? note this please down for later discussion. For now it is fine.

2020-08-24 15:06 UTC, h9k commented on modules/registrars/rrpproxy/sql/mod_rrpproxy_zones.php
> +$mod_rrpproxy_zones = array(
This file was generated by phpMyAdmin.
What I did is start with an empty table, and fill it up by running the TLD Sync.
Since this requires one request per domain to get certain zone information, it leads to the API user being temporarily banned.
This is why I created this initial import. The module will update the zone info in blocks over time to keep them up to date.

2020-08-25 05:30 UTC, merged

2020-09-05 08:37 UTC, papakai commented
:tada: This PR is included in version 0.2.0 :tada:

The release is available on:
- [GitHub release](https://github.com/rrpproxy/whmcs-rrpproxy-registrar/releases/tag/v0.2.0)
- [WHMCS Marketplace Product Version](https://marketplace.whmcs.com/product/5573)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: