Use GetZoneInfo to determine domain features
rrpproxy/whmcs-rrpproxy-registrar pull request #15
Opened 2020-09-05 08:55 UTC by h9k

2020-09-10 11:53 UTC, papakai requested changes

2020-09-10 11:53 UTC, papakai commented on package.json
> +    "cz-conventional-changelog": "^3.3.0",
not necessary

commitizen is installed globally. I never had the requirement to specify cz-conventional-changelog explicitely.
Can you provide more insights why you are forwading this? I just know these changes are part of the github readme of commitizen, right? If you had no explicit (technical) reason, I suggest not doing this.

2020-09-10 11:53 UTC, papakai commented on package.json
> +  "config": {
not necessary, see previous comment

2020-09-10 11:58 UTC, papakai commented
When the above is resolved, feel free to directly merge. ty!

2020-09-10 18:11 UTC, h9k commented on package.json
> +    "cz-conventional-changelog": "^3.3.0",
I had the issue where `git cz` would again just open the normal commit vi, so I ran that initialization command `commitizen init cz-conventional-changelog --save-dev --save-exact` again, and that added the stuff to package.json.

2020-09-10 18:16 UTC, papakai commented on package.json
> +    "cz-conventional-changelog": "^3.3.0",
hm, i checked something:
`npm i -g cz-conventional-changelog` ftw!

Please just delete the commit introducing the package.json changes. When having the above module installed globally, it does what you need.

2020-09-12 04:18 UTC, h9k commented on package.json
> +    "cz-conventional-changelog": "^3.3.0",
Allright! Done.

2020-09-12 04:32 UTC, merged

2020-09-14 06:22 UTC, h9k commented
:tada: This PR is included in version 0.3.0 :tada:

The release is available on:
- [GitHub release](https://github.com/rrpproxy/whmcs-rrpproxy-registrar/releases/tag/v0.3.0)
- [WHMCS Marketplace Product Version](https://marketplace.whmcs.com/product/5573)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: