feat(getdomaininformation): fixes index access; extended to provide add. data for import purposes
rrpproxy/whmcs-rrpproxy-registrar pull request #48
Opened 2021-07-27 09:21 UTC by papakai

2021-07-27 09:23 UTC, papakai commented
I'll also be testing around, but if you could support here a bit @h9k, would be great.

2021-07-28 17:27 UTC, h9k requested changes

2021-07-28 17:27 UTC, h9k commented on modules/registrars/keysystems/keysystems.php
> +        foreach ($pnames as $prop) {
Something is wrong with this loop. $prop is never used and $key is not defined, so I assume you wanted to use $prop insted of $key.

2021-08-04 08:08 UTC, h9k approved these changes

2021-08-04 08:08 UTC, merged

2021-08-04 08:11 UTC, papakai commented
:tada: This PR is included in version 0.8.0 :tada:

The release is available on:
- [GitHub release](https://github.com/rrpproxy/whmcs-rrpproxy-registrar/releases/tag/v0.8.0)
- [WHMCS Marketplace Product Version](https://marketplace.whmcs.com/product/5573)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: