Bugfix/contacts
rrpproxy/whmcs-rrpproxy-registrar pull request #59
Opened 2021-11-01 11:50 UTC by h9k

2021-11-01 12:48 UTC, papakai requested changes
Use double quotes over single quotes for array key access.

2021-11-01 13:23 UTC, h9k commented
> Use double quotes over single quotes for array key access.

done!

2021-11-01 16:38 UTC, papakai approved these changes

2021-11-02 06:44 UTC, papakai commented on modules/registrars/keysystems/lib/RRPProxyClient.php
> +                "First Name" => '',
Keep empty Strings please also over double quotes. thanks!

2021-11-02 06:50 UTC, papakai requested changes
See my inline comment. ty

2021-11-02 06:56 UTC, h9k commented on modules/registrars/keysystems/lib/RRPProxyClient.php
> +                "First Name" => '',
ok, done!

2021-11-02 06:58 UTC, merged

2021-11-02 07:00 UTC, papakai commented
:tada: This PR is included in version 0.10.1 :tada:

The release is available on:
- [GitHub release](https://github.com/rrpproxy/whmcs-rrpproxy-registrar/releases/tag/v0.10.1)
- [WHMCS Marketplace Product Version](https://marketplace.whmcs.com/product/5573)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: