feat(transfer): improve domain transfer handling
rrpproxy/whmcs-rrpproxy-registrar pull request #61
Opened 2021-11-01 11:52 UTC by h9k

re #56

2021-11-01 12:28 UTC, papakai requested changes
Please use double quotes instead of single quotes.

2021-11-01 13:16 UTC, h9k commented
> Please use double quotes instead of single quotes.

done!

2021-11-01 16:34 UTC, papakai approved these changes

2021-11-02 06:46 UTC, merged

2021-11-02 06:48 UTC, papakai commented
:tada: This PR is included in version 0.9.0 :tada:

The release is available on:
- [GitHub release](https://github.com/rrpproxy/whmcs-rrpproxy-registrar/releases/tag/v0.9.0)
- [WHMCS Marketplace Product Version](https://marketplace.whmcs.com/product/5573)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: